# Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Project information
site_name: WSO2 Security and Compliance Documentation
site_description: Documentation for WSO2 Security and Compliance
site_author: WSO2
site_url: https://security.docs.wso2.com/en/latest/

# Repository
repo_name: wso2/docs-security
repo_url: https://github.com/wso2/docs-security
edit_uri: https://github.com/wso2/docs-security/edit/main/en/docs/

# Copyright
copyright: WSO2 Security and Compliance - Documentation

# Configuration
theme:
  name: material
  palette:
    primary: deep-orange
    accent: deep-orange
  custom_dir: theme/material
  logo: images/logo.svg
  favicon: images/favicon.png
  highlightjs: true
  feature:
    tabs: true
  language: 'en'

# Navigation
nav:
  - 'WSO2 Security and Compliance Documentation': 'index.md'
  - 'Security Processes and Programs':
    - 'Vulnerability Reporting Guidelines': 'vuln-mgt/vulnerability-reporting-guidelines.md'
    - 'Vulnerability Management Process': 'vuln-mgt/vulnerability-management-process.md'
    - 'Reward and Acknowledgement Program':
      - 'Reward and Acknowledgement Program': 'vuln-mgt/reward-and-acknowledgement-program.md'
      - 'Acknowledgements': 'vuln-mgt/acknowledgements.md'
    - 'CVE and Incident Clarifications':
      - 'WSO2 Product CVE Clarifications':
        - '': 'cves-and-incidents/wso2-product-cve-clarifications.md'
        - 'CVE-2019-6512': 'cves-and-incidents/cve-clarifications/CVE-2019-6512.md'
        - 'CVE-2019-6513': 'cves-and-incidents/cve-clarifications/CVE-2019-6513.md'
        - 'CVE-2019-6515': 'cves-and-incidents/cve-clarifications/CVE-2019-6515.md'
        - 'CVE-2019-17571': 'cves-and-incidents/cve-clarifications/CVE-2019-17571.md'
        - 'CVE-2020-1938': 'cves-and-incidents/cve-clarifications/CVE-2020-1938.md'
        - 'CVE-2020-13226': 'cves-and-incidents/cve-clarifications/CVE-2020-13226.md'
        - 'ZDI-CAN-13449': 'cves-and-incidents/cve-clarifications/ZDI-CAN-13449.md'
      - 'CVE to WSO2 Security Advisory Mapping': 'cves-and-incidents/cve-to-wso2-security-advisory-mapping.md'
      - 'Security Incident Clarifications':
        - '': 'cves-and-incidents/security-incident-clarifications.md'
        - '2020':
          - '': 'cves-and-incidents/incident-clarifications/2020/overview.md'
          - 'SolarWinds SUNBURST breach': 'cves-and-incidents/incident-clarifications/2020/solarwinds-sunburst-breach.md'
        - '2021':
          - '': 'cves-and-incidents/incident-clarifications/2021/overview.md'
          - 'Codecov supply chain breach': 'cves-and-incidents/incident-clarifications/2021/codecov-supply-chain-breach.md'
          - 'NPM packages coa and rc Compromised': 'cves-and-incidents/incident-clarifications/2021/npm-packages-coa-and-rc-compromised.md'
          - 'NPM package UA-Parser-JS Compromised': 'cves-and-incidents/incident-clarifications/2021/npm-package-ua-parser-js-compromised.md'
  - 'Security Advisories':
    - 'Overview': 
      - '': 'security-advisories/overview.md'
      - '2016 Advisories': 
        - '': 'security-advisories/2016/2016-advisories.md'
        - 'WSO2-2016-0092': 'security-advisories/2016/WSO2-2016-0092.md'
        - 'WSO2-2016-0095': 'security-advisories/2016/WSO2-2016-0095.md'
        - 'WSO2-2016-0096': 'security-advisories/2016/WSO2-2016-0096.md'
        - 'WSO2-2016-0098': 'security-advisories/2016/WSO2-2016-0098.md'
        - 'WSO2-2016-0101': 'security-advisories/2016/WSO2-2016-0101.md'
        - 'WSO2-2016-0104': 'security-advisories/2016/WSO2-2016-0104.md'
        - 'WSO2-2016-0127': 'security-advisories/2016/WSO2-2016-0127.md'
        - 'WSO2-2016-0135': 'security-advisories/2016/WSO2-2016-0135.md'
        - 'WSO2-2016-0138': 'security-advisories/2016/WSO2-2016-0138.md'
        - 'WSO2-2016-0140': 'security-advisories/2016/WSO2-2016-0140.md'
        - 'WSO2-2016-0141': 'security-advisories/2016/WSO2-2016-0141.md'
        - 'WSO2-2016-0150': 'security-advisories/2016/WSO2-2016-0150.md'
        - 'WSO2-2016-0151': 'security-advisories/2016/WSO2-2016-0151.md'
        - 'WSO2-2016-0156': 'security-advisories/2016/WSO2-2016-0156.md'
        - 'WSO2-2016-0158': 'security-advisories/2016/WSO2-2016-0158.md'
        - 'WSO2-2016-0159': 'security-advisories/2016/WSO2-2016-0159.md'
        - 'WSO2-2016-0168': 'security-advisories/2016/WSO2-2016-0168.md'
        - 'WSO2-2016-0169': 'security-advisories/2016/WSO2-2016-0169.md'
        - 'WSO2-2016-0170': 'security-advisories/2016/WSO2-2016-0170.md'
      - '2017 Advisories': 
        - '': 'security-advisories/2017/2017-advisories.md'
        - 'WSO2-2017-0177': 'security-advisories/2017/WSO2-2017-0177.md'
        - 'WSO2-2017-0179': 'security-advisories/2017/WSO2-2017-0179.md'
        - 'WSO2-2017-0182': 'security-advisories/2017/WSO2-2017-0182.md'
        - 'WSO2-2017-0183': 'security-advisories/2017/WSO2-2017-0183.md'
        - 'WSO2-2017-0184': 'security-advisories/2017/WSO2-2017-0184.md'
        - 'WSO2-2017-0185': 'security-advisories/2017/WSO2-2017-0185.md'
        - 'WSO2-2017-0186': 'security-advisories/2017/WSO2-2017-0186.md'
        - 'WSO2-2017-0187': 'security-advisories/2017/WSO2-2017-0187.md'
        - 'WSO2-2017-0188': 'security-advisories/2017/WSO2-2017-0188.md'
        - 'WSO2-2017-0190': 'security-advisories/2017/WSO2-2017-0190.md'
        - 'WSO2-2017-0197': 'security-advisories/2017/WSO2-2017-0197.md'
        - 'WSO2-2017-0198': 'security-advisories/2017/WSO2-2017-0198.md'
        - 'WSO2-2017-0203': 'security-advisories/2017/WSO2-2017-0203.md'
        - 'WSO2-2017-0210': 'security-advisories/2017/WSO2-2017-0210.md'
        - 'WSO2-2017-0212': 'security-advisories/2017/WSO2-2017-0212.md'
        - 'WSO2-2017-0218': 'security-advisories/2017/WSO2-2017-0218.md'
        - 'WSO2-2017-0223': 'security-advisories/2017/WSO2-2017-0223.md'
        - 'WSO2-2017-0235': 'security-advisories/2017/WSO2-2017-0235.md'
        - 'WSO2-2017-0254': 'security-advisories/2017/WSO2-2017-0254.md'
        - 'WSO2-2017-0255': 'security-advisories/2017/WSO2-2017-0255.md'
        - 'WSO2-2017-0257': 'security-advisories/2017/WSO2-2017-0257.md'
        - 'WSO2-2017-0260': 'security-advisories/2017/WSO2-2017-0260.md'
        - 'WSO2-2017-0261': 'security-advisories/2017/WSO2-2017-0261.md'
        - 'WSO2-2017-0262': 'security-advisories/2017/WSO2-2017-0262.md'
        - 'WSO2-2017-0263': 'security-advisories/2017/WSO2-2017-0263.md'
        - 'WSO2-2017-0265': 'security-advisories/2017/WSO2-2017-0265.md'
        - 'WSO2-2017-0266': 'security-advisories/2017/WSO2-2017-0266.md'
        - 'WSO2-2017-0267': 'security-advisories/2017/WSO2-2017-0267.md'
        - 'WSO2-2017-0289': 'security-advisories/2017/WSO2-2017-0289.md'
        - 'WSO2-2017-0326': 'security-advisories/2017/WSO2-2017-0326.md'
      - '2018 Advisories': 
        - '': 'security-advisories/2018/2018-advisories.md'
        - 'WSO2-2018-0462': 'security-advisories/2018/WSO2-2018-0462.md'
      - '2019 Advisories': 
        - '': 'security-advisories/2019/2019-advisories.md'
        - 'WSO2-2019-0432': 'security-advisories/2019/WSO2-2019-0432.md'
        - 'WSO2-2019-0486': 'security-advisories/2019/WSO2-2019-0486.md'
        - 'WSO2-2019-0501': 'security-advisories/2019/WSO2-2019-0501.md'
        - 'WSO2-2019-0504': 'security-advisories/2019/WSO2-2019-0504.md'
        - 'WSO2-2019-0545': 'security-advisories/2019/WSO2-2019-0545.md'
        - 'WSO2-2019-0554': 'security-advisories/2019/WSO2-2019-0554.md'
        - 'WSO2-2019-0571': 'security-advisories/2019/WSO2-2019-0571.md'
        - 'WSO2-2019-0597': 'security-advisories/2019/WSO2-2019-0597.md'
        - 'WSO2-2019-0598': 'security-advisories/2019/WSO2-2019-0598.md'
        - 'WSO2-2019-0600': 'security-advisories/2019/WSO2-2019-0600.md'
        - 'WSO2-2019-0616': 'security-advisories/2019/WSO2-2019-0616.md'
        - 'WSO2-2019-0618': 'security-advisories/2019/WSO2-2019-0618.md'
        - 'WSO2-2019-0621': 'security-advisories/2019/WSO2-2019-0621.md'
        - 'WSO2-2019-0624': 'security-advisories/2019/WSO2-2019-0624.md'
        - 'WSO2-2019-0625': 'security-advisories/2019/WSO2-2019-0625.md'
        - 'WSO2-2019-0633': 'security-advisories/2019/WSO2-2019-0633.md'
        - 'WSO2-2019-0634': 'security-advisories/2019/WSO2-2019-0634.md'
        - 'WSO2-2019-0635': 'security-advisories/2019/WSO2-2019-0635.md'
        - 'WSO2-2019-0636': 'security-advisories/2019/WSO2-2019-0636.md'
        - 'WSO2-2019-0644': 'security-advisories/2019/WSO2-2019-0644.md'
        - 'WSO2-2019-0645': 'security-advisories/2019/WSO2-2019-0645.md'
        - 'WSO2-2019-0646': 'security-advisories/2019/WSO2-2019-0646.md'
        - 'WSO2-2019-0647': 'security-advisories/2019/WSO2-2019-0647.md'
        - 'WSO2-2019-0653': 'security-advisories/2019/WSO2-2019-0653.md'
        - 'WSO2-2019-0655': 'security-advisories/2019/WSO2-2019-0655.md'
        - 'WSO2-2019-0656': 'security-advisories/2019/WSO2-2019-0656.md'
        - 'WSO2-2019-0658': 'security-advisories/2019/WSO2-2019-0658.md'
        - 'WSO2-2019-0661': 'security-advisories/2019/WSO2-2019-0661.md'
      - '2020 Advisories': 
        - '': 'security-advisories/2020/2020-advisories.md'
        - 'WSO2-2018-0537': 'security-advisories/2020/WSO2-2018-0537.md'
        - 'WSO2-2019-0651': 'security-advisories/2020/WSO2-2019-0651.md'
        - 'WSO2-2019-0663': 'security-advisories/2020/WSO2-2019-0663.md'
        - 'WSO2-2019-0665': 'security-advisories/2020/WSO2-2019-0665.md'
        - 'WSO2-2019-0666': 'security-advisories/2020/WSO2-2019-0666.md'
        - 'WSO2-2019-0667': 'security-advisories/2020/WSO2-2019-0667.md'
        - 'WSO2-2019-0670': 'security-advisories/2020/WSO2-2019-0670.md'
        - 'WSO2-2019-0673': 'security-advisories/2020/WSO2-2019-0673.md'
        - 'WSO2-2019-0681': 'security-advisories/2020/WSO2-2019-0681.md'
        - 'WSO2-2020-0684': 'security-advisories/2020/WSO2-2020-0684.md'
        - 'WSO2-2020-0685': 'security-advisories/2020/WSO2-2020-0685.md'
        - 'WSO2-2020-0687': 'security-advisories/2020/WSO2-2020-0687.md'
        - 'WSO2-2020-0688': 'security-advisories/2020/WSO2-2020-0688.md'
        - 'WSO2-2020-0689': 'security-advisories/2020/WSO2-2020-0689.md'
        - 'WSO2-2020-0690': 'security-advisories/2020/WSO2-2020-0690.md'
        - 'WSO2-2020-0693': 'security-advisories/2020/WSO2-2020-0693.md'
        - 'WSO2-2020-0698': 'security-advisories/2020/WSO2-2020-0698.md'
        - 'WSO2-2020-0699': 'security-advisories/2020/WSO2-2020-0699.md'
        - 'WSO2-2020-0700': 'security-advisories/2020/WSO2-2020-0700.md'
        - 'WSO2-2020-0701': 'security-advisories/2020/WSO2-2020-0701.md'
        - 'WSO2-2020-0702': 'security-advisories/2020/WSO2-2020-0702.md'
        - 'WSO2-2020-0705': 'security-advisories/2020/WSO2-2020-0705.md'
        - 'WSO2-2020-0706': 'security-advisories/2020/WSO2-2020-0706.md'
        - 'WSO2-2020-0707': 'security-advisories/2020/WSO2-2020-0707.md'
        - 'WSO2-2020-0711': 'security-advisories/2020/WSO2-2020-0711.md'
        - 'WSO2-2020-0713': 'security-advisories/2020/WSO2-2020-0713.md'
        - 'WSO2-2020-0718': 'security-advisories/2020/WSO2-2020-0718.md'
        - 'WSO2-2020-0722': 'security-advisories/2020/WSO2-2020-0722.md'
        - 'WSO2-2020-0727': 'security-advisories/2020/WSO2-2020-0727.md'
        - 'WSO2-2020-0728': 'security-advisories/2020/WSO2-2020-0728.md'
        - 'WSO2-2020-0730': 'security-advisories/2020/WSO2-2020-0730.md'
        - 'WSO2-2020-0731': 'security-advisories/2020/WSO2-2020-0731.md'
        - 'WSO2-2020-0734': 'security-advisories/2020/WSO2-2020-0734.md'
        - 'WSO2-2020-0742': 'security-advisories/2020/WSO2-2020-0742.md'
        - 'WSO2-2020-0747': 'security-advisories/2020/WSO2-2020-0747.md'
        - 'WSO2-2020-0751': 'security-advisories/2020/WSO2-2020-0751.md'
        - 'WSO2-2020-0752': 'security-advisories/2020/WSO2-2020-0752.md'
        - 'WSO2-2020-0755': 'security-advisories/2020/WSO2-2020-0755.md'
        - 'WSO2-2020-0781': 'security-advisories/2020/WSO2-2020-0781.md'
        - 'WSO2-2020-0843': 'security-advisories/2020/WSO2-2020-0843.md'
        - 'WSO2-2020-0864': 'security-advisories/2020/WSO2-2020-0864.md'
        - 'WSO2-2020-0873': 'security-advisories/2020/WSO2-2020-0873.md'
        - 'WSO2-2020-1119': 'security-advisories/2020/WSO2-2020-1119.md'
        - 'WSO2-2020-1139': 'security-advisories/2020/WSO2-2020-1139.md'
        - 'WSO2-2020-1196': 'security-advisories/2020/WSO2-2020-1196.md'
      - '2021 Advisories': 
        - '': 'security-advisories/2021/2021-advisories.md'
        - 'WSO2-2020-0716': 'security-advisories/2021/WSO2-2020-0716.md'
        - 'WSO2-2020-0787': 'security-advisories/2021/WSO2-2020-0787.md'
        - 'WSO2-2020-0803': 'security-advisories/2021/WSO2-2020-0803.md'
        - 'WSO2-2020-0840': 'security-advisories/2021/WSO2-2020-0840.md'
        - 'WSO2-2020-1106': 'security-advisories/2021/WSO2-2020-1106.md'
        - 'WSO2-2020-1130': 'security-advisories/2021/WSO2-2020-1130.md'
        - 'WSO2-2020-1132': 'security-advisories/2021/WSO2-2020-1132.md'
        - 'WSO2-2020-1224': 'security-advisories/2021/WSO2-2020-1224.md'
        - 'WSO2-2020-1225': 'security-advisories/2021/WSO2-2020-1225.md'
        - 'WSO2-2020-1233': 'security-advisories/2021/WSO2-2020-1233.md'
        - 'WSO2-2021-1238': 'security-advisories/2021/WSO2-2021-1238.md'
        - 'WSO2-2021-1258': 'security-advisories/2021/WSO2-2021-1258.md'
        - 'WSO2-2021-1260': 'security-advisories/2021/WSO2-2021-1260.md'
        - 'WSO2-2021-1261': 'security-advisories/2021/WSO2-2021-1261.md'
        - 'WSO2-2021-1289': 'security-advisories/2021/WSO2-2021-1289.md'
        - 'WSO2-2021-1292': 'security-advisories/2021/WSO2-2021-1292.md'
        - 'WSO2-2021-1314': 'security-advisories/2021/WSO2-2021-1314.md'
        - 'WSO2-2021-1315': 'security-advisories/2021/WSO2-2021-1315.md'
        - 'WSO2-2021-1338': 'security-advisories/2021/WSO2-2021-1338.md'
        - 'WSO2-2021-1347': 'security-advisories/2021/WSO2-2021-1347.md'
        - 'WSO2-2021-1350': 'security-advisories/2021/WSO2-2021-1350.md'
        - 'WSO2-2021-1351': 'security-advisories/2021/WSO2-2021-1351.md'
        - 'WSO2-2021-1357': 'security-advisories/2021/WSO2-2021-1357.md'
        - 'WSO2-2021-1453': 'security-advisories/2021/WSO2-2021-1453.md'
        - 'WSO2-2021-1497': 'security-advisories/2021/WSO2-2021-1497.md'
        - 'WSO2-2021-1411': 'security-advisories/2021/WSO2-2021-1411.md'
  - 'Product Security':
    - 'Secure Software Development Process': 'product-security/secure-software-development-process.md'
    - 'Security Guidelines for Production Deployment': 'product-security/security-guidelines-for-production-deployment.md'
    - 'Docker Image Scanning Process': 'product-security/docker-image-scanning-process.md'
    - 'Third-party Dependency Scanning Process': 'product-security/third-party-dependency-scanning-process.md'
    - 'Compliance':
      - 'OWASP Software Assurance Maturity Model (OWASP SAMM)': 'product-security/compliance/owasp-samm.md'
      - 'OWASP Application Security Verification Standard (OWASP ASVS)': 'product-security/compliance/owasp-asvs.md'
      - 'FIPS-140': 'product-security/compliance/fips-140.md'
  #- Cloud Security:
  - 'Secure Engineering Guidelines': 
    - '': 'secure-engineering/index.md'
    - 'WSO2 Secure Coding Guidelines': 
      - '': 'secure-engineering/secure-coding-guidlines/index.md'
      - 'Introduction': 'secure-engineering/secure-coding-guidlines/introduction.md'
      - 'OWASP Top 10 - 2017 Prevention': 'secure-engineering/secure-coding-guidlines/owasp-t10-2017-prevention.md'
      - 'OWASP Top 10 - 2013 Prevention': 'secure-engineering/secure-coding-guidlines/owasp-t10-2013-prevention.md'
      - 'OWASP Mobile Top 10 Prevention': 'secure-engineering/secure-coding-guidlines/owasp-mobile-t10-prevention.md'
      - 'General Recommendations for Secure Coding': 'secure-engineering/secure-coding-guidlines/general-recommendations-for-secure-coding.md'
      - 'Tooling Recommendations for Secure Coding': 'secure-engineering/secure-coding-guidlines/tooling-recommendations-for-secure-coding.md'
    - 'Threat Modeling Guidelines': 'secure-engineering/threat-modeling-guidelines.md'
  - 'Compliance': 
    - 'ISO/IEC 27001': 'compliance/iso27001.md'
    - 'GDPR': 'compliance/gdpr.md'
    - 'CCPA': 'compliance/ccpa.md'
    - 'LGPD': 'compliance/lgpd.md'
    - 'Policies': 'compliance/policies.md'
  - 'Community':
    - 'Webinars':
      - '': 'community/webinars.md'
      - 'Perfecting Security Governance: This Is How We Do It': 'community/webinars/perfecting-security-governance-this-is-how-we-do-it.md'
  - '': 'page-not-found.md'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      use_pygments: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# plugins
plugins:
  - search

# Extra
extra_css:
  - assets/lib/highlightjs/default.min.css
  - assets/css/theme.css
extra_javascript:
  - assets/lib/highlightjs/highlight.min.js
  - assets/js/theme.js
  - assets/lib/backtotop/js/util.js
  - assets/lib/backtotop/js/main.js
extra:
  social:
    - type: github
      link: https://github.com/wso2
    - type: twitter
      link: https://twitter.com/wso2
    - type: linkedin
      link: https://www.linkedin.com/company/wso2
  site_version: 1.0.0
  cp_timeframe: 2015-2021
  nav_list:
    - WSO2 Security and Compliance Documentation
    - Security Processes and Programs
    - Security Advisories
    - Product Security
    - Secure Engineering Guidelines
    - Compliance
    - Community
